store_3d/mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    index, about, contact, register, gallery, login_view, logout_view, edit_profile,
    delete_profile, manage_products, update_order, create_order, manage_orders,
    update_product, delete_product, articles, create_product, filter_products,
    add_to_cart, remove_from_cart, view_cart, store, filter_products_in_cart,
    randomize_order_dates, filter_order, contact_form_submit,
    UserListAPIView, ProductListAPIView, OrderListAPIView, delete_order, purchase,
    profile, CategoriesListAPIView, process_payment
)

urlpatterns = [
    # Index
    path('', index, name='index'),

    # API Endpoints
    path('api/users/', UserListAPIView.as_view(), name='user-list'),
    path('api/products/', ProductListAPIView.as_view(), name='product-list'),
    path('api/orders/', OrderListAPIView.as_view(), name='order-list'),
    path('api/categories/', CategoriesListAPIView.as_view(), name='categories-list'),

    # Authentication
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),

    # Static Pages
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('contact_form_submit/', contact_form_submit, name='contact_form_submit'),
    path('gallery/', gallery, name='gallery'),
    path('articles/', articles, name='articles'),

    # User Profile
    path('profile/', profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('delete_profile/', delete_profile, name='delete_profile'),

    # Products
    path('products/', manage_products, name='manage_products'),
    path('update_product/<int:product_id>/', update_product, name='update_product'),
    path('create_product/', create_product, name='create_product'),
    path('filter_products/<int:days>/', filter_products, name='filter_products'),
    path('delete_product/<int:product_id>/', delete_product, name='delete_product'),

    # Orders
    path('orders/', manage_orders, name='manage_orders'),
    path('orders/create/', create_order, name='create_order'),
    path('update_order/<int:order_id>/', update_order, name='update_order'),
    path('delete_order/<int:order_id>/', delete_order, name='delete_order'),
    path('filter_order/<int:days>/', filter_order, name='filter_order'),
    path('randomize_order_dates/', randomize_order_dates, name='randomize_order_dates'),

    # Store
    path('store/', store, name='store'),

    # Cart
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='cart'),
    path('remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('filter_products_in_cart/<int:days>/', filter_products_in_cart, name='filter_products_in_cart'),

    # Purchase
    path('purchase/', purchase, name='purchase'),
    path('process_payment/', process_payment, name='process_payment'),
    # Redirect
    path('', RedirectView.as_view(url='/media/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_3d/store_3d/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('__debug__/', include("debug_toolbar.urls")),
]

# URLs for serving media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_3d/mainapp/models.py
from django.contrib.auth.models import AbstractBaseUser, Group
from django.db import models
from django.contrib.auth.models import BaseUserManager


class UserManager(BaseUserManager):
    """Manager for user model"""
    def create_user(self, email, username, password=None):
        """Creates a new user"""
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """Creates and saves a new superuser"""
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """ Class for users in the system"""
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    patronymic_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)
    at_data = models.DateTimeField(auto_now_add=True)
    groups = models.ManyToManyField(Group, blank=True, related_name='users')
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        """Returns the username"""
        return self.username

    def has_perm(self, perm, obj=None):
        """Determines if the user has a specific permission."""
        return True

    def has_module_perms(self, app_label):
        """Determines if the user has permissions to view the app 'app_label'."""
        return True

    @property
    def is_staff(self):
        """Determines if the user is a staff member."""
        return self.is_admin


class Category(models.Model):
    """Model representing a category."""
    name = models.CharField(max_length=60, unique=True)

    def __str__(self):
        """Returns the name of the Category ."""
        return self.name


class Product(models.Model):
    """Model representing a product."""
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=0)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, default=1)
    image = models.ImageField(upload_to='product_images/')
    stl_file = models.FileField(upload_to='stl_files/')
    at_data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns the name of the Product."""
        return self.name


class Article(models.Model):
    """Model representing an article."""
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        """Returns the title of the article."""
        return self.title


class Order(models.Model):
    """Order model"""
    PENDING = 'P'
    COMPLETED = 'C'
    CANCELLED = 'X'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (COMPLETED, 'Completed'),
        (CANCELLED, 'Cancelled'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=PENDING)
    at_data = models.DateTimeField(auto_now_add=True)


class Cart(models.Model):
    """Model representing a shopping cart."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)


class CartItem(models.Model):
    """Model representing an item in a shopping cart."""
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    description = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        """Override the save method to update name, description, and price based on the linked product."""
        self.name = self.product.name
        self.description = self.product.description
        self.price = self.product.price
        super().save(*args, **kwargs)


class Image(models.Model):
    """Model representing an image."""
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='img')

    def __str__(self):
        """String representation of the image object."""
        return self.title

store_3d/mainapp/forms.py
from django import forms
from .models import User, Product, Order


class LoginForm(forms.Form):
    """Form for login"""
    email = forms.EmailField(label='Ваш email')
    password = forms.CharField(label='Ваш пароль', widget=forms.PasswordInput)


class UserProfileForm(forms.ModelForm):
    """Form for updating user profile"""
    password = forms.CharField(widget=forms.PasswordInput(), label='Пароль', required=False)
    password_confirmation = forms.CharField(widget=forms.PasswordInput(), label='Подтверждение пароля', required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'patronymic_name', 'phone', 'street', 'city',
                  'region', 'postal_code']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirmation = cleaned_data.get('password_confirmation')

        if password and password_confirmation and password != password_confirmation:
            raise forms.ValidationError("Пароль и подтверждение пароля не совпадают.")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            initial_data = {
                'username': self.instance.username,
                'email': self.instance.email,
                'first_name': self.instance.first_name,
                'last_name': self.instance.last_name,
                'patronymic_name': self.instance.patronymic_name,
                'phone': self.instance.phone,
                'street': self.instance.street,
                'city': self.instance.city,
                'region': self.instance.region,
                'postal_code': self.instance.postal_code
            }
            self.initial = initial_data

    def clean(self):
        """Clean method to validate password confirmation"""
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password and password != password_confirmation:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data


class UserForm(forms.ModelForm):
    """ Form for creating new users"""
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'phone']
        labels = {
            'username': '',
            'password': '',
            'email': '',
            'phone': '',
            }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Ваш ник'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Ваш пароль'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Ваш еmail'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Ваш телефон'}),
            'address': forms.TextInput(attrs={'placeholder': 'Ваш адрес'}),
        }


class ProductForm(forms.ModelForm):
    """Form for creating new products"""
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'quantity', 'category_id']
        labels = {
            'name': '',
            'price': '',
            'quantity': '',
            'description': '',
            'category_id': ''

        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Товар'}),
            'price': forms.NumberInput(attrs={'placeholder': 'Цена'}),
            'quantity': forms.NumberInput(attrs={'placeholder': 'Кол-во'}),
            'description': forms.TextInput(attrs={'placeholder': 'Описание'}),
            'category_id': forms.TextInput(attrs={'placeholder': 'Категория'}),
        }


class ImageForm(forms.Form):
    """Form for uploading images"""
    image = forms.ImageField()


class OrderForm(forms.ModelForm):
    """Form for creating new Orders"""
    class Meta:
        model = Order
        fields = ['user', 'product']

store_3d/mainapp/templates/mainapp/articles.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<section id="faq" class="faq section-bg">
    <div class="container">
                <div class="section-title">
                    <h2>{{ title }}</h2>
                    <h4>
                        "Откройте для себя мир 3D-печати с нашими увлекательными статьями. Узнайте о последних технологических достижениях, применении в различных отраслях и получите полезные советы от экспертов."
                    </h4>
                </div>
                <div class="faq-list">
                    <ul>
                        {% for article in articles %}
                        <li data-aos="fade-up">
                            <i class="bx bx-help-circle icon-help"></i>
                            <a href="#faq-list-{{ forloop.counter }}" class="collapse collapsed" aria-expanded="false" data-bs-toggle="collapse">
                                {{ article.title }}
                                <i class="bx bx-chevron-down icon-show"></i>
                                <i class="bx bx-chevron-up icon-close"></i>
                            </a>
                            <div id="faq-list-{{ forloop.counter }}" class="collapse" data-bs-parent=".faq-list">
                                {% if article.content %}
                                    {{ article.content | safe }}
                                {% endif %}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
        </div>
    </div>
</section>
{% endblock %}

store_3d/mainapp/templates/mainapp/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ contact }}{% endblock %}

{% block content %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">
        <div class="row">

          <div class="col-lg-4">
            <div class="info">
            <div class="address">
              <i class="bi bi-geo-alt"></i>
                <h4>Наш адрес:</h4>
                <p>{{ city }}, {{ address }}</p>
            </div>

            <div class="email">
              <i class="bi bi-envelope"></i>
                <h4>Наш email:</h4>
                <p>{{ email_store }}</p>
          </div>

          <div class="phone">
            <i class="las la-phone-volume la-3x"></i>
              <h4> Наш телефон:</h4>
              <p>{{ phone }}</p>
          </div>

          </div>

          </div>
       <div class="col-lg-6">
            <form action="/contact_form_submit/" method="post" role="form" class="php-email-form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 form-group">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Ваш Email" required>
                    </div>
                </div>
                <div class="form-group mt-3">
                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Тема" required>
                </div>
                <div class="form-group mt-3">
                    <textarea class="form-control" name="message" rows="5" placeholder="Сообщение" required></textarea>
                </div>
                <div class="my-3">
                    <div class="loading">Загрузка</div>
                    <div class="sent-message">Ваше сообщение отправлено. Спасибо!</div>
                    <div class="error-message"></div>
                </div>
                <div class="text-center"><button type="submit">Отправить сообщение</button></div>
            </form>

          </div>

        </div>

      </div>
    </section>
{% endblock %}

store_3d/mainapp/templates/mainapp/create_article.html
<div class="col">
    <p>
        Инновационные материалы для 3D печати представляют собой ключевой аспект развития этой технологии, расширяя её возможности и области применения. Вот несколько видов инновационных материалов и их потенциальные применения в 3D печати:
    </p>

    <div class="card mb-3" style="max-width: max-content;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="/static/img/product_image/image15.jpg" class="img-fluid rounded-start" alt="..." style="float: left; margin-right: 10px;">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Масштабные модели зданий и городских пространств</h5>
                    <p>
                        Использование 3D печати для создания масштабных моделей зданий и городских пространств открывает уникальные возможности для архитектурных и градостроительных проектов. Эти модели представляют собой точные трехмерные воспроизведения реальных объектов, которые могут быть использованы для различных целей, включая демонстрацию проектов заказчикам, презентации на городских планировочных совещаниях, а также в качестве обучающих материалов.

                        Одним из ключевых преимуществ 3D печати в этой области является возможность создания высокодетализированных моделей с минимальными усилиями. Точные данные из архитектурных программных средств могут быть легко преобразованы в файлы для 3D печати, что позволяет быстро и эффективно создавать модели любой сложности.

                        Благодаря 3D печати архитекторы и градостроители могут легко визуализировать свои идеи и концепции, а также проверить их на практике, создавая физические прототипы до начала строительства. Это способствует более эффективной работе над проектами, помогая выявить потенциальные проблемы и улучшить концепции еще на ранних стадиях.

                        Еще одним важным аспектом является возможность создания масштабных моделей с использованием различных материалов, включая пластик, смолы, металлы и композитные материалы. Это позволяет адаптировать модели к конкретным требованиям проекта и обеспечивает широкий выбор вариантов отделки и цветовых решений.

                        Кроме того, 3D печать позволяет создавать модели различных масштабов - от крупных городских кварталов до отдельных зданий или даже их частей. Это дает возможность более детально изучать архитектурные решения и взаимосвязь между различными элементами городской инфраструктуры.

                        В целом, использование 3D печати для создания масштабных моделей зданий и городских пространств является эффективным инструментом для архитекторов, градостроителей и проектировщиков, позволяющим улучшить процесс проектирования, улучшить визуализацию и повысить качество конечного результата.            </div>

                    </p>
        </div>
    </div>

    <div class="card mb-3" style="max-width: max-content;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="/static/img/product_image/image16.jpg" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8" style="float: right;">
                <div class="card-body">
                    <h5 class="card-title">
                        Масштабные модели зданий и городских пространств
                    </h5>
                    <p>
                        3D печать также применяется для создания индивидуальных имплантатов, которые используются в различных областях медицины, включая стоматологию, ортопедию и пластическую хирургию. Благодаря возможности точного моделирования и изготовления имплантатов, адаптированных к конкретным анатомическим условиям пациента, удается достичь оптимальных результатов лечения. Это также сокращает время операции и восстановления, что является ключевым фактором в быстром восстановлении пациентов.
                    </p>
                </div>
            </div>
        </div>
    </div>


    <div class="card mb-3" style="max-width: max-content;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="/static/img/product_image/image18.jpg" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8" style="float: right;">
                <div class="card-body">
                    <h5 class="card-title">
                        Перспективы использования 3D печати в жилищном строительстве
                    </h5>
                    <p>
                        С каждым годом технологии 3D печати становятся все более доступными и совершенными, что открывает новые возможности в области медицины. В будущем мы можем ожидать еще более точных и функциональных протезов и имплантатов, а также более сложных и реалистичных моделей органов. Кроме того, развитие биопринтинга позволит создавать органные ткани и органы из биологически совместимых материалов, что имеет потенциал революционизировать область трансплантологии.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <p>
        3D печать претерпевает быстрое развитие и играет все более значимую роль в медицине. Создание индивидуальных протезов, имплантатов и моделей органов открывает новые перспективы в лечении и образовании, содействуя повышению качества медицинской помощи и улучшению жизни пациентов.
    </p>
</div>

store_3d/mainapp/templates/mainapp/create_order.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<section id="create-order" class="section-bg">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center">
        <div class="section-title">
          <h2>{{ title }}</h2>
        </div>
        <!-- Форма для создания нового заказа -->
        <form method="post" class="mb-4">
            {% csrf_token %}

          {% if form.instance.pk %}
          <h3>Редактирование товара: {{ product }}</h3>
          {{ form.as_p }}
                <button type="submit" name="update_product" class="btn btn-primary">Изменить</button>
                <a href="{% url 'manage_products' %}" class="btn btn-primary">Отмена</a>

            {% else %}
             {{ form.as_p }}
             <button type="submit" name="create_product" class="btn btn-primary">Создать новый товар</button>

            {% endif %}
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

store_3d/mainapp/templates/mainapp/forbidden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Доступ запрещен</title>
</head>
<body>
    <h1>Доступ запрещен</h1>
    <p>{{ message }}</p>
    <a href="{% url 'index' %}">Вернуться на главную страницу</a>
</body>
</html>

store_3d/mainapp/templates/mainapp/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ main }} {% endblock %}

{% block content %}
<section id="gallery" class="gallery">
  <div class="container">
    <div class="section-title">
      <h2>{{ title }}</h2>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row g-0">
      {% for i in gallery_range %}
      <div class="col-lg-3 col-md-4">
        <div class="gallery-item">
          <a href="{% static 'img/gallery/gallery-' %}{{ i }}.png" class="gallery-lightbox">
            <img src="{% static 'img/gallery/gallery-' %}{{ i }}.png" class="img-fluid img-thumbnail">
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

store_3d/mainapp/templates/mainapp/profile.html
{% extends 'base.html' %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<div id="update-success-message" style="display: none; position: fixed; top: 10%; left: 50%; transform: translate(-50%, -50%); background-color: #28a745; color: #fff; padding: 10px 20px; border-radius: 5px; z-index: 1000;" class="alert" role="alert"></div>


<section id="user-profile" class="section-bg">
    <div class="container">
        <div class="section-title">
            <h2>Профиль пользователя: {{user.username}}(ID: {{user.id}})</h2>
            <div class="col text-md-start">
              {% csrf_token %}
              <button type="submit" class="btn red col-3">Удалить профиль</button>
              <form action="{% url 'delete_profile' %}" method="post" role="form" onsubmit="return confirm('Вы уверены, что хотите удалить свой профиль? Все данные будут удалены.');">
              </form>
            </div>
        </div>

        {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <div class="row">
            <form action="{% url 'edit_profile' %}" method="post" role="form">
                {% csrf_token %}
                <div class="col-8 offset-3 text-md-center">
                    <div class="form-group row mt-2">
                        <label for="id_username" class="col-sm-4 col-form-label text-md-end">Никнейм:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_username" name="username" value="{{ user.username }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_email" class="col-sm-4 col-form-label text-md-end">Email:</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="id_email" name="email" value="{{ user.email }}">
                        </div>
                    </div>
                    <p class="col mt-3 mb-0 grey">
                        Для изменения пароля, введите новый пароль и подтверждение.
                    </p>

                    <div class="form-group row mt-2">
                        <label for="id_password" class="col-sm-4 col-form-label text-md-end">Пароль:</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="id_password" name="password">
                        </div>
                    </div>
                    <div class="form-group row mt-2 mb-5">
                        <label for="id_password_confirmation" class="col-sm-4 col-form-label text-md-end">Подтверждение пароля:</label>
                        <div class="col-sm-8">
                        <input type="password" class="form-control" id="id_password_confirmation" name="password_confirmation">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_first_name" class="col-sm-4 col-form-label text-md-end">Имя:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_last_name" class="col-sm-4 col-form-label text-md-end">Фамилия:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user.last_name }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_patronymic_name" class="col-sm-4 col-form-label text-md-end">Отчество:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_patronymic_name" name="patronymic_name" value="{{ user.patronymic_name }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_phone" class="col-sm-4 col-form-label text-md-end">Телефон:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_phone" name="phone" value="{{ user.phone }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_street" class="col-sm-4 col-form-label text-md-end">Улица:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_street" name="street" value="{{ user.street }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_city" class="col-sm-4 col-form-label text-md-end">Город:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_city" name="city" value="{{ user.city }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_region" class="col-sm-4 col-form-label text-md-end">Регион:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_region" name="region" value="{{ user.region }}">
                        </div>
                    </div>
                    <div class="form-group row mt-2">
                        <label for="id_postal_code" class="col-sm-4 col-form-label text-md-end">Почтовый индекс:</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="id_postal_code" name="postal_code" value="{{ user.postal_code }}">
                        </div>
                    </div>
                      <button type="submit" class="col-5 btn blue mt-4">Обновить данные</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}